import 'bootstrap/dist/css/bootstrap.css'
import 'bootstrap-icons/font/bootstrap-icons.css'

import Head from 'next/head'

export default function Create() {
  return (
    <div>
      <Head>
        <title>ESP32 - Controle de Acesso</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <div>
        <nav className="navbar navbar-home navbar-expand-lg navbar-dark bg-primary">
          <a className="navbar-brand" href="#">Controle de Acesso - Cadastro</a>
        </nav>

      </div>
    </div>
  )
}
