import 'bootstrap/dist/css/bootstrap.css'
import 'bootstrap-icons/font/bootstrap-icons.css'

import Head from 'next/head'
import Link from 'next/link';


export default function Home() {
  return (
    <div>
      <Head>
        <title>ESP32 - Controle de Acesso</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <div>
        <nav className="navbar navbar-home navbar-expand-lg navbar-dark bg-primary">
          <a className="navbar-brand" href="#">Controle de Acesso - Usuários</a>
        </nav>

        <hr></hr>

        <div className='wrapper-home'>
          <table className="table table-striped table-hover">
              <thead className="table-dark">
                <tr>
                  <th scope="col">Código</th>
                  <th scope="col">Nome</th>
                  <th scope="col">E-Mail</th>
                  <th scope="col">Data de expiração</th>
                  <th scope="col">Status</th>
                  <th scope="col">Editar</th>
                  <th scope="col">Excluir</th>
                </tr>
              </thead>
              <tbody>
                <tr>
                  <th scope="row">1</th>
                  <td>Adri Silva</td>
                  <td>adrisilva0002@gmail.com</td>
                  <td>30/11/2022</td>
                  <td><span className="badge bg-success">Ativo</span></td>
                  <td><button type="button" className="btn btn-outline-primary btn-sm"><i className="bi bi-pencil"></i></button></td>
                  <td><button type="button" className="btn btn-outline-danger btn-sm"><i className="bi bi-trash"></i></button></td>
                </tr>
                <tr>
                  <th scope="row">1</th>
                  <td>Zé Zinho</td>
                  <td>papoco@gmail.com</td>
                  <td>20/06/2022</td>
                  <td><span className="badge bg-danger">Inativo</span></td>
                  <td><button type="button" className="btn btn-outline-primary btn-sm"><i className="bi bi-pencil"></i></button></td>
                  <td><button type="button" className="btn btn-outline-danger btn-sm"><i className="bi bi-trash"></i></button></td>
                </tr>
              </tbody>
          </table>

          <Link href="/create">
            <a className="btn btn-sm btn-secondary" type="button">Adicionar Usuário</a>
          </Link>
          
        </div>
      </div>
    </div>
  )
}
